all: base_types.o bitfields.o circular_references.o unions.o

base_types.o: base_types.c
	gcc -g -c base_types.c -o base_types.o

bitfields.o: bitfields.c
	gcc -g -c bitfields.c -o bitfields.o

circular_references.o: circular_references.c
	gcc -g -c circular_references.c -o circular_references.o

unions.o: unions.c
	gcc -g -c unions.c -o unions.o
